CREATE TABLE LOGISTICSYSTEM.TBL_USERINFO(
	IDX INT,
    USERID VARCHAR(50),
    PASSWORD VARCHAR(50),
    USERNAME VARCHAR(50),
    STATE VARCHAR(50),
    PERMISSION VARCHAR(50),
    USERNUMBER VARCHAR(50),
    USEREMAIL VARCHAR(50),
    USERINCIDENTDAY DATETIME,
    CREATEDATE DATETIME,
    CREATOR VARCHAR(50),
    COMPANYCODE VARCHAR(50),
    USERNAME_EN VARCHAR(50),
    USERNUMBERTYPE VARCHAR(50));
    
ALTER TABLE LOGISTICSYSTEM.TBL_USERINFO ADD CONSTRAINT IDX PRIMARY KEY (IDX);

CREATE TABLE LOGISTICSYSTEM.CODECREATOR(
	CODE DECIMAL(5),
    CODEBUFFER DECIMAL(5),
    TYPE INT(3)
);

CREATE TABLE LOGISTICSYSTEM.TBL_COMPANYINFO(
	IDX INT,
	COMPANYCODE VARCHAR(200),
	COMPANYNAME VARCHAR(200),
	COMPANYADDRESS VARCHAR(200),
	COMPANYPOSTNUMBER VARCHAR(200),
	COMPANYSECURITYNUMBER VARCHAR(200),
	REPRESENTATIVE VARCHAR(200),
	REPRESENTATIVENUMBER VARCHAR(200),
	COMPANYNUMBER VARCHAR(200),
	COMPANYFAX VARCHAR(200),
	COMPANYEMAIL VARCHAR(200),
	REPRESENTATIVEEMAIL VARCHAR(200),
	COMPANYACCOUNTNUMBER VARCHAR(200),
	COMPANYACCOUNTBANK VARCHAR(200),
	COMPANYACCOUNTBANKCODE VARCHAR(200),
	COMPANYACCOUNTBANKCODENAME VARCHAR(200),
	COMPANYACCOUNTOWNERNAME VARCHAR(200),
	COMPANYESTABLISHMENTDATE DATETIME,
	CREATEDATE DATETIME,
	CREATOR VARCHAR(200),
	STATE VARCHAR(200),
	ORDERADDRESS VARCHAR(200),
	COMPANYNAME_EN VARCHAR(200),
	COMPANYADDRESS_EN VARCHAR(200),
	REPRESENTATIVE_EN VARCHAR(200),
	ORDERADDRESS_EN VARCHAR(200),
	COMPANYNUMBERTYPE VARCHAR(200),
	COMPANYFAXTYPE VARCHAR(200),
	COMPANYREPRESENTATIVENUMBER VARCHAR(200)
);

CREATE TABLE LOGISTICSYSTEM.TBL_PRODUCTINFO(
	IDX INT,
	PRODUCTCODE VARCHAR(200),
	PRODUCTNAME VARCHAR(200),
	PRODUCTTYPE VARCHAR(200),
	PRODUCTSPEC VARCHAR(200),
	PRODUCTTAX INT,
	PRODUCTACQUIRER VARCHAR(200),
	PRODUCTMANUFACTURER VARCHAR(200),
	PRODUCTCOST DECIMAL(65),
	PRODUCTCOSTNOTTAX DECIMAL(65),
	PRODUCTCOSTTAX DECIMAL(65),
	PRODUCTFACTORYPRICE DECIMAL(65),
	PRODUCTFACTORYPRICENOTTAX DECIMAL(65),
	PRODUCTFACTORYPRICETAX DECIMAL(65),
	PRODUCTRETAILPRICE DECIMAL(65),
	PRODUCTRETAILPRICENOTTAX DECIMAL(65),
	PRODUCTRETAILPRICETAX DECIMAL(65),
	PRODUCTPRICE DECIMAL(65),
	PRODUCTPRICENOTTAX DECIMAL(65),
	PRODUCTPRICETAX DECIMAL(65),
	BARCODE VARCHAR(200),
	QRCODE VARCHAR(200),
	OTHER VARCHAR(200),
	CREATEDATE DATETIME,
	CREATER VARCHAR(200),
	STATE VARCHAR(200),
	COMPANYCODE VARCHAR(200)
);

CREATE TABLE LOGISITCSYSTEM.TBL_CONNECT(
	USERID VARCHAR(200),
	CONNECTABLE DATETIME,
	STATE VARCHAR(200),
	LANGUAGE VARCHAR(200),
	IPADDRESS VARCHAR(200)
);